---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricefalconweb
  labels:
    app: pricefalconweb
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pricefalconweb
  template:
    metadata:
      labels:
        app: pricefalconweb
    spec:
      containers:
        - name: pricefalcon
          image: ghcr.io/eliotjones/falconweb:latest
          ports:
            - name: httpin
              containerPort: 6110
          env:
            - name: ConnectionStrings__Default
              valueFrom:
                secretKeyRef:
                  name: connectionstring
                  key: connection-string
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: PRICE_FALCON_SENDGRID
              valueFrom:
                secretKeyRef:
                  name: sendgridapikey
                  key: api-key
            - name: SiteUrl
              value: https://pricefalcon.me
---
apiVersion: v1
kind: Service
metadata:
  name: pricefalconweb
spec:
  ports:
    - name: http
      targetPort: httpin
      port: 80
    - name: https
      targetPort: httpin
      port: 443
  selector:
    app: pricefalconweb
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pricefalconweb
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: pricefalconweb
              servicePort: http
  tls:
    - hosts:
        - pricefalcon.me
      secretName: pricefalcon-me-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricefalconcrawl
  labels:
    app: pricefalconcrawl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricefalconcrawl
  template:
    metadata:
      labels:
        app: pricefalconcrawl
    spec:
      containers:
        - name: pricefalcon
          image: ghcr.io/eliotjones/falconcrawl:latest
          ports:
            - containerPort: 6770
          env:
            - name: ConnectionStrings__Default
              valueFrom:
                secretKeyRef:
                  name: connectionstring
                  key: connection-string
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
