name: Docker

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  WEB_IMAGE_NAME: falconweb
  CRAWL_IMAGE_NAME: falconcrawl

jobs:
  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build web image
        run: pwd && docker build -f docker/web/Dockerfile -t $WEB_IMAGE_NAME .
        working-directory: .

      - name: Build crawler image
        run: docker build -f docker/crawler/Dockerfile -t $CRAWL_IMAGE_NAME .

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          WEB_IMAGE_ID=ghcr.io/eliotjones/$WEB_IMAGE_NAME
          CRAWL_IMAGE_ID=ghcr.io/eliotjones/$CRAWL_IMAGE_NAME

          # Use the commit SHA as the version.
          VERSION=${{ github.sha }}

          echo WEB_IMAGE_ID=$WEB_IMAGE_ID
          echo CRAWL_IMAGE_ID=$CRAWL_IMAGE_ID
          echo VERSION=$VERSION

          docker tag $WEB_IMAGE_NAME $WEB_IMAGE_ID:$VERSION
          docker push $WEB_IMAGE_ID:$VERSION

          docker tag $CRAWL_IMAGE_NAME $CRAWL_IMAGE_ID:$VERSION
          docker push $CRAWL_IMAGE_ID:$VERSION

      - name: Update deployment image id
        uses: datamonsters/replace-action@master
        with:
          files: "kubernetes/deployment.yaml"
          replacements: "ghcr.io/eliotjones/falconweb:latest=ghcr.io/eliotjones/falconweb:${{ github.sha }},ghcr.io/eliotjones/falconcrawl:latest=ghcr.io/eliotjones/falconcrawl:${{ github.sha }}"

      - name: Deploy using kubectl
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: apply -f kubernetes/deployment.yaml
